### PR TITLE
Test solution

### PR DESCRIPTION
**Pull request by jdkangas**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Should I merge? As noted previously only the latest commit in this PR will be scored.

**Comment by jdkangas** [comment]
yes

**Comment by jdkangas** [comment]
Here's another one:

I made a commit, but I don't see anyway to initiate a pull request.

https://github.com/jdkangas/cyto-challenge/commit/fae2361f9e1e67463ec993ba879cecb5f3148224

**Comment by MartinHjelmare** [comment]
Don't you see this button?

github_pr

**Comment by jdkangas** [comment]
I definitely see that button, but the resulting screen didn't obviously
take me to my branch, but I figured out I needed to compare across forks
and then the "Compare and Pull" button shows up.

Best,

-josh

**Pull request merged**
