### PR TITLE
Our submission for challenge 2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Thanks for your submission!

**Comment by MartinHjelmare** [comment]
Hi!

It looks like your submission contained too few rows. Challenge 2 should have 8000 rows in the csv file.

**Comment by ghost** [comment]
Thank you for the information! We will sort this out.

**Comment by ghost** [comment]
We had missing lines because there were about 500 images that our program could not read. We had the same problem with the training data. Has anyone else encountered this problem? We added empty lines to our new submission, hopefully the scoring system can handle this.

**Pull request merged**
