### PR TITLE
added field level predictions

### PR DESCRIPTION
**Pull request by jdkangas**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Hi! Should I merge?

**Comment by jdkangas** [comment]
Yes please.

On Jun 14, 2017 1:29 PM, "Martin Hjelmare" <notifications@github.com> wrote:

Hi! Should I merge?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CellProfiling/cyto-challenge/pull/14#issuecomment-308502424>,
or mute the thread

**Comment by jdkangas** [comment]
Hello Martin,

I was under the impression that our max F1 score would be kept after
multiple submissions.  It appears that it went down with the last merge.
Do I need to submit separate branches?

Best,

-josh

**Comment by MartinHjelmare** [comment]
I don't think your max F1 score went down. Do you have commit hashes I can compare? Devin just asked me to sort on highest F1 score, so I've made that change now.

**Comment by MartinHjelmare** [comment]
Do you mean between your two commits in this pull request? The scoring is only done after merge, so yes if you want to try different solutions you have to make different pull requests.

**Comment by jdkangas** [comment]
I made three commits so far with three different solutions that I'd like
considered:
3700ce0bf08b0db888c251039fb3494e89f83e03
2ee4e92322fa7947d46d873d3cbef6388dc08c9b
20299f5be4e19531a7a89687040254280573dca4

Have all of these been scored?

-josh

**Comment by jdkangas** [comment]
I wasn't able to see the pull request button after one of these pushes so I
only made two pull requests.

-josh

**Comment by MartinHjelmare** [comment]
Only these two have been scored:
3700ce0bf08b0db888c251039fb3494e89f83e03
20299f5be4e19531a7a89687040254280573dca4

**Comment by jdkangas** [comment]
Do you see a commit with this id?
 46c9091

I did a commit and push more recently than those recently and git returned
that number in my terminal, but I'm not seeing it on the github website in
order to request a pull.

-josh

**Comment by jdkangas** [comment]
My apologies.  You were right about the highest score being correct.  I was
looking at the wrong column.  I'm still missing that commit though...

**Comment by MartinHjelmare** [comment]
No worries. I can see that commit in your branch on your fork, but it was not included in this PR, so was not included in the merge. If you want to include it, just make a new PR.

Edit: Although make sure you rebase properly first on upstream master. Take care though, cause it's binary files you're submitting. I managed to mess that up earlier when I tried to rebase. Might be easiest to make a new branch based off a freshed pulled master, and then encrypt again and commit.

**Comment by jdkangas** [comment]
Maybe my gitfu is weak, but I'm not seeing my branch on the github website
to do a pull request.

The two times it worked, a "Compare and Pull" button showed up and I
clicked it.

Is there another way to initiate a pull?

When I click New Pull Request, I just don't see my branch at all.

-josh

**Comment by MartinHjelmare** [comment]
Here's the branch with that commit included:
https://github.com/jdkangas/cyto-challenge/tree/test-solution

You should always be able to select the branch of interest, then click "New pull request" right off the branch button, under "### commits".

**Pull request merged**
