### PR TITLE
New pull request for challenge 2

### PR DESCRIPTION
**Pull request by ghost**
Old files were removed before adding new ones and creating this pull request. Hopefully everything works now. In new submission all 8000 samples have predictions.

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Super job!!! Now it works! :tada: 

Sorry for all the work to get your submission in. Thanks!

**Comment by ghost** [comment]
Great! Thank you for all your help!

**Comment by MartinHjelmare** [comment]
PS: Please send some slides to our cyto challenge gmail, about your solution, if you haven't already.

**Comment by ghost** [comment]
Okay, I will.

**Pull request merged**
