### PR TITLE
Add field level submission for challenge 2 and 3

### PR DESCRIPTION
**Pull request by jdkangas**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Hi! Ok to merge?

**Comment by jdkangas** [comment]
Yes.  Ok to merge.  Thanks!

**Comment by MartinHjelmare** [comment]
Great, thanks!

**Comment by jdkangas** [comment]
Hello Martin,

Can you please provide me with some assistance in resolving the scoring
issue for challenge 3?  Thanks!

-josh

**Comment by MartinHjelmare** [comment]
Hi!

It looks like you are using the old image test set for challenge 3. There was a problem of duplicated images with the originally uploaded image set. Please download `rare_events_test.tar` again, if you downloaded it before 2017-06-12:16.00 CET, and run your model again. The image set should contain 257 FOVs.

Sorry for the inconvenience!

**Comment by devsullivan** [comment]
Hey Josh! 

Alternatively, you can delete image 230 and decrement all remaining IDs so that your results have 257 lines. 

Cheers, 
Devin

**Comment by devsullivan** [comment]
PS, are you here at CYTO? Taco Tuesday?

**Pull request merged**
