### PR TITLE
Submission for challenge 2

### PR DESCRIPTION
**Pull request by ghost**
New pull request for challenge 2.

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
I'm sorry, it seems my rebase messed up the pgp encryption. I think the best solution is that you:

- Save your unencrypted csv files somewhere safe, in another directory.
- Remove your local cyto-challenge fork directory on your computer.
- Remove your forked cyto-challenge repo  at github.com.
- Start over from the beginning by forking our repo and then cloning your fork etc.

I'm sorry about the inconvenience.

**Comment by MartinHjelmare** [comment]
Wait, I can see if I can pull your branch and merge locally instead. Don't delete your fork at github.

**Comment by MartinHjelmare** [comment]
No, even just pulling your `kaisli` branch directly and decrypting that fails for your two encrypted csv files. I think you need to remove the encrypted csv.gpg files and encrypt the csv files again, and commit and push again. Then I can try to pull again and test it. If it works I can merge locally and push directly so you don't need to make a new PR.

**Comment by ghost** [comment]
Oh, I just deleted it before reading your comment. Sorry! Should I try from the beginning now or did you have time to pull?

**Comment by MartinHjelmare** [comment]
I had time to pull, but see my latest comment above. It seems something didn't go right with your latest encryption. Edit: Oh yeah, I forced push when you had the PR open, so it's all my fault. Very sorry.

**Comment by MartinHjelmare** [comment]
Ok, so now just start from the beginning. I'm crossing my fingers here.

**Pull request merged**
