### PR TITLE
Add submission for challenge 2

### PR DESCRIPTION
**Pull request by pqiu**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
@pqiu Ok, to merge?

**Comment by pqiu** [comment]
Devin informed me a problem with the data for challenge 3, which requires
me to update my challenge 3 submission. I have created another update.
Could you please merge the other one? Thanks a lot.

Best,
Peng

**Comment by MartinHjelmare** [comment]
Ok, I merged your other PR. Thanks!

I'll close this PR.

**Comment by pqiu** [comment]
Thank you very much.  I can see the F-scores now.  They are very close to
what I anticipated. Some localizations are pretty difficult to predict.
Thanks.

Best,
Peng

**Comment by MartinHjelmare** [comment]
Thanks for the feedback and your submission!

**Pull request closed without merging**
