### PR TITLE
New solution file for challenge 2

### PR DESCRIPTION
**Pull request by ghost**
There are now 8000 lines in the file.

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
You need to rebase your branch to resolve conflicts. You should not work on master, but create a separate branch. Try this:
```
git checkout -b kaisli master
git branch -D master
git fetch upstream master
git checkout master
git checkout kaisli
git rebase master
git push origin kaisli
```
Then open a new pull request from the kaisli branch.

**Comment by ghost** [comment]
Thank you for the instructions! However, I am still having problems with the pull request. I followed the instructions but got an error after git checkout master (pathspec 'master' did not match any file(s) known to git). So, when trying to open pull request there's the same error as previously, "Can't automatically merge".

**Comment by MartinHjelmare** [comment]
Did you run `git fetch upstream master` before that?

**Comment by MartinHjelmare** [comment]
Let me know if you want to try again. Otherwise I can probably fix it for you.

**Comment by ghost** [comment]
Yes, I did run the fetch command and it didn't produce any errors. It would be great if you could fix this, I don't know what to try next. Thank you for your help!

**Comment by MartinHjelmare** [comment]
Please open a new pull request from your kaisli branch and target the master branch of our repo. I think I can fix it, but your branch can't be the master branch, I think.

**Pull request closed without merging**
